### ISSUE TITLE
pos_cashier - Al seleccionar cajero con lector de código de barras bloquea el menú

### ISSUE THREAD

**Issue by JGarcia-Panach** [rgbconsulting/rgb-pos#1]
Hola @admin-rgbconsulting, 
primero de todo, muchas gracias por compartir el módulo, queríamos añadir esa funcionalidad a nuestro TPV y era justo lo que buscábamos.

La prueba que hemos hecho es la siguiente
- Tenemos 3 cajeros: Adm, Comercial1 y Comercial2. y cada uno tiene asignado un código de barras con el formato adecuado (041*)
- El TPV actual está asignado al usuario Admin, con lo cual es el cajero que nos aparece por defecto.
- Seleccionamos desde el menú el usuario Comercial1 - lo cambia correctamente
- Seleccionamos con lector de código de barras el usuario Comercial2 - lo cambia correctamente
- Ahora seleccionamos desde el menú el usuario Admin - se queda bloqueado con el usuario Comercial2

Si queremos seleccionar con lector de código de barras otro usuario sí que lo permite, pero no por el menú de cajeros.

Hemos probado modificando un par de líneas y el problema se soluciona.
Son las líneas 37 y 38 del static/js
https://github.com/rgbconsulting/rgb-addons/blob/8.0/pos_cashier/static/src/js/pos.js#L37

Hemos cambiado:
       self.pos.user = user;
       self.renderElement();
por:
       self.pos.cashier = user;
       self.refresh();

Si os parece bien, mi compañero Juan Carlos podría preparar el PR.

Un saludo y gracias otra vez

**Comment by admin-rgbconsulting** [comment]
Hola @JGarcia-Panach 

Nos alegra que os haya servido de utilidad el módulo. Os agradecemos la prueba realizada así como el detalle tanto en la detección del error, como de la solución.

Los cambios que nos proponéis parecen correctos, sin embargo vamos a intentar reproducir el error y validar los cambios internamente durante la próxima semana. El módulo se hizo precisamente para clientes sin lector (IPads, etc.)

Notificaremos este Issue cuando lo hayamos echo.
P.D. no es necesario el PR, aunque gracias de antemano por vuestra predisposición.

Saldos y gracias!

**Comment by JGarcia-Panach** [comment]
Todo perfecto. Muchas gracias!

**Comment by admin-rgbconsulting** [comment]
Hola @JGarcia-Panach ,
Finalmente hemos validado el error y confirmado el fix propuesto.
Gracias y un cordial saludo.

**Comment by JGarcia-Panach** [comment]
Muchas gracias!!
Un saludo
